// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohlvnwpsfqjorocrifmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9obHZud3BzZnFqb3JvY3JpZm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzY2ODIsImV4cCI6MjA3MjA1MjY4Mn0.MDCG5IRXmVlC4C9iRn_MsbC94qNX8CNKG7pPbw0nOP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});